spring: # test profile
  datasource:
    url: "jdbc:h2:mem:instagram"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: "b9ba6041-9927-4bf8-9bfa-fdaf95ae5a9b"
  access-token-expire-time: 1800000
  refresh-token-expire-time: 2592000000